kind: dataset/stream/multimodal
name: k4a-2d-kpt
mdetadata:
  labels:
    app: openpack-benchmarks
    version: 1.0.0
    multimodal: true
spec:
  kinect2dKpt:
    kind: dataset/stream/keypoint
    spec:
      poseEstimationModel: mmpose-hrnet-w48-posetrack18-384x288-posewarper-stage2
      path:
        dir: ${path.openpack.rootdir}/${user.name}/kinect/2d-kpt/${..poseEstimationModel}/single
        fname: ${session}.json
      stats:
        mean:
          x: 631.23
          y: 523.68
        std:
          x: 100.98
          y: 111.06
      frame_rate: 15
      nodes:
        0: nose
        1: left_eye
        2: right_eye
        3: left_ear
        4: right_ear
        5: left_shoulder
        6: right_shoulder
        7: left_elbow
        8: right_elbow
        9: left_wrist
        10: right_wrist
        11: left_hip
        12: right_hip
        13: left_knee
        14: right_knee
        15: left_ankle
        16: right_ankle
