name: Test
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        python-version: ["3.10"]
        poetry-version: ["1.2.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Dependencis and Run Tests
        run: |
          poetry install
          export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
          poetry run pytest --cov --ignore=openpack_torch/utils/test_helper.py
        shell: bash
